# Generated by Django 5.2.8 on 2025-11-12 15:07

import django.db.models.deletion
import django_lifecycle.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers_alter_user_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Careers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=255)),
                (
                    "education",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HS", "High School"),
                            ("CL", "College"),
                            ("BA", "Bachelors"),
                            ("MA", "Masters"),
                            ("PhD", "Doctorate"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "experience",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IN", "Intern"),
                            ("JR", "Junior"),
                            ("MD", "Mid"),
                            ("SR", "Senior"),
                            ("LD", "Lead"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "preferred_careers",
                    models.ManyToManyField(
                        blank=True, related_name="interested_users", to="users.careers"
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True, related_name="user_profiles", to="users.skill"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
