# Generated by Django 5.2.8 on 2025-11-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_cv_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="suggested_roles",
            field=models.ManyToManyField(
                blank=True, related_name="suggested_users", to="users.careers"
            ),
        ),
    ]
