# Generated by Django 5.2.8 on 2025-11-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userprofile_suggested_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cv_full",
            field=models.TextField(blank=True, null=True),
        ),
    ]
