# Generated by Django 5.2.8 on 2025-11-14 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userprofile_cv_full"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedCV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="cvs")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_cv",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
