# Generated by Django 5.2.8 on 2025-11-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="education",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="experience",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
