# Generated by Django 5.2.8 on 2025-11-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_userprofile_education_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IN", "Intern"),
                    ("JR", "Junior"),
                    ("MD", "Mid"),
                    ("SR", "Senior"),
                    ("LD", "Lead"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
