# Generated by Django 5.2.8 on 2025-11-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0004_add_cv_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("is_remote", models.BooleanField(default=False)),
                (
                    "recommended_experience",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("Internship", "Internship"),
                            ("Part-time", "Part-time"),
                            ("Full-time", "Full-time"),
                            ("Freelance", "Freelance"),
                        ],
                        default="Full-time",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "required_skills",
                    models.ManyToManyField(
                        blank=True, related_name="jobs", to="users.skill"
                    ),
                ),
            ],
        ),
    ]
