# Generated by Django 5.2.8 on 2025-11-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0004_add_cv_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("platform", models.CharField(blank=True, max_length=100, null=True)),
                ("url", models.URLField(max_length=1024)),
                (
                    "cost",
                    models.CharField(
                        choices=[("Free", "Free"), ("Paid", "Paid")],
                        default="Free",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "related_skills",
                    models.ManyToManyField(
                        blank=True, related_name="learning_resources", to="users.skill"
                    ),
                ),
            ],
        ),
    ]
